# Generated by Django 5.1.1 on 2024-10-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_transaction_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total_transaction',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
