# Generated by Django 5.1.1 on 2024-10-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_transaction_total_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioshare',
            name='average_price_per_share',
            field=models.DecimalField(decimal_places=12, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='portfolioshare',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='portfolioshare',
            name='number_share',
            field=models.IntegerField(default=0),
        ),
    ]
