# Generated by Django 5.1.1 on 2024-10-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_portfolioshare_average_price_per_share_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
