# Generated by Django 5.1.1 on 2024-10-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0005_rename_quatity_transaction_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioshare',
            name='average_price_per_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
