# Generated by Django 5.1.1 on 2024-10-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_alter_portfolioshare_average_price_per_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
