# Generated by Django 5.1.1 on 2024-10-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_alter_transaction_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_share_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
