# Generated by Django 5.1.1 on 2024-10-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_alter_transaction_price_per_share_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_per_share',
            new_name='max_price_per_share',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='total_share_price',
            new_name='total_shares_price',
        ),
    ]
