# Generated by Django 5.1.1 on 2024-10-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_portfolioshare_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
