# Generated by Django 5.1.1 on 2024-10-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_transaction_profit_loss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True),
        ),
    ]
