# Generated by Django 5.1.1 on 2024-10-10 01:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_alter_transaction_profit_loss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='profit_loss',
        ),
        migrations.AddField(
            model_name='portfolioshare',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True),
        ),
    ]
