# Generated by Django 5.1.1 on 2024-10-10 02:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_remove_transaction_profit_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioshare',
            name='total_in_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True),
        ),
    ]
