# Generated by Django 5.1.1 on 2024-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0015_portfoliosharehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioshare',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4),
        ),
    ]
